# Build HTML and man pages, put the man pages underneath html/man/ so they
# get served as well.
[build]
  command = "make html && make man && mv _build/man _build/html"
  publish = "_build/html"

# PDF artifacts are transparently proxied to the build server
[[redirects]]
  from = "/pdf/*"
  to = "https://build.syncthing.net/guestAuth/repository/download/Web_BuildDocumentation/.lastSuccessful/:splat"
  status = 200
